<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE testset [
	<!ELEMENT description (#PCDATA) >

	<!ELEMENT query (#PCDATA) >

	<!ELEMENT format (#PCDATA) >

	<!ELEMENT test (description, query, format) >

	<!ATTLIST test
			critical (YES|NO) #REQUIRED
	>
	
	<!ELEMENT testset (test*) >
]>

<testset>

	<test critical="YES">
		<description>
			Do all contigs have the correct number of mappings?
		</description>

		<query>
            select C.contig_id,nreads,count(distinct seq_id) as mapping_count
            from CONTIG C left join SEQ2CONTIG M using(contig_id)
            group by contig_id having nreads != mapping_count
		</query>
		
		<format>
			Contig {0,number,#} has nreads={1,number,#} but {2,number,#} mappings
		</format>
	</test>

	<test critical="YES">
		<description>
			Are there any orphan contigs?
		</description>
		
		<query>
			select contig_id,C.created,length,name
			from CONTIG C left join PROJECT P using(project_id)
			where C.nreads = 0
		</query>
		
		<format>
			Contig {0,number,#} created at {1,time} on {1,date}, length {2,number,#}bp, in project {3}, has nreads=0
		</format>
	</test>

	<test critical="YES">
		<description>
			Are there any duplicate reads?
		</description>
		
		<query>
		        select R.readname,DR.hits,CC.contig_id,P.name,CC.length,CC.nreads,CC.created,M.coffset,M.direction
		        from DUPLICATEREADS DR left join (READNAME R,SEQ2READ SR,SEQ2CONTIG M,CURRENTCONTIGS CC,PROJECT P)
		        on (DR.read_id=R.read_id)
		        where R.read_id=SR.read_id and SR.seq_id=M.seq_id and M.contig_id=CC.contig_id and CC.project_id=P.project_id
		        order by DR.read_id asc,CC.contig_id asc
		</query>
		
		<format>
			Read {0} appears {1,number,#} times and is in current contig {2,number,#} ({3}, {4,number,#} bp, {5,number,#} reads, created at {6,time} on {6,date}) from {7,number,#} in {8} sense
		</format>
	</test>

	<test critical="YES">
		<description>
			Are there any current contigs which share duplicate reads?
		</description>
		
		<query>
				select CCA.contig_id,CCA.length,CCA.nreads,CCA.created,PA.name,
					CCB.contig_id,CCB.length,CCB.nreads,CCB.created,PB.name,
       				count(*) as `links`
				from CURRENTCONTIGS CCA,PROJECT PA,SEQ2CONTIG MA,SEQ2READ SRA,
					 CURRENTCONTIGS CCB,PROJECT PB,SEQ2CONTIG MB,SEQ2READ SRB
				where CCA.contig_id=MA.contig_id and MA.seq_id=SRA.seq_id
				and SRA.read_id=SRB.read_id
				and SRB.seq_id=MB.seq_id and MB.contig_id=CCB.contig_id
				and CCA.contig_id &lt; CCB.contig_id
				and CCA.project_id=PA.project_id and CCB.project_id=PB.project_id
				group by CCA.contig_id,CCB.contig_id
				order by CCA.contig_id asc,CCB.contig_id asc	
		</query>
		
		<format>
			Contigs {0,number,#} ({4}, {1,number,#} bp, {2,number,#} reads, created at {3,time} on {3,date}) and {5,number,#} ({9}, {6,number,#} bp, {7,number,#} reads, created at {8,time} on {8,date}) share {10,number,#} {10,choice,1#read|1&lt;reads} in common.
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all sequences have a corresponding sequence-to-read mapping?
		</description>
		
		<query>

			select SEQUENCE.seq_id from SEQUENCE left join SEQ2READ
			using (seq_id)
			where SEQ2READ.seq_id is null
		</query>
		
		<format>
			Sequence {0,number,#} has no associated sequence-to-read mapping
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all reads have valid sequence data?
		</description>

		<query>
			select READNAME.read_id,readname from READNAME left join SEQ2READ
			using (read_id)
			where seq_id is null
		</query>
		
		<format>
			Read {0,number,#} ({1}) has no associated sequence
		</format>
	</test>

	<test critical="NO">
		<description>
			Do all reads have a template?
		</description>

		<query>
			select RI.read_id,RN.readname from
			(READINFO RI left join READNAME RN using (read_id))
			left join TEMPLATE using (template_id)
			where name is null
		</query>
		
		<format>
			Read {0,number,#} ({1}) has no associated template
		</format>
	</test>

	<test critical="NO">
		<description>
			Do all templates have a ligation?
		</description>

		<query>
			select template_id,TEMPLATE.name from TEMPLATE left join LIGATION
			using (ligation_id)
			where LIGATION.name is null
		</query>
		
		<format>
			Template {0,number,#} ({1}) has no associated ligation
		</format>
	</test>

	<test critical="NO">
		<description>
			Do all ligations have a clone?
		</description>

		<query>
			select ligation_id,LIGATION.name from LIGATION left join CLONE
			using(clone_id)
			where CLONE.name is null
		</query>
		
		<format>
			Ligation {0,number,#} ({1}) has no associated clone
		</format>
	</test>

</testset>
