<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE testset [
	<!ELEMENT description (#PCDATA) >

	<!ELEMENT query (#PCDATA) >

	<!ELEMENT format (#PCDATA) >

	<!ELEMENT test (description, query, format) >

	<!ATTLIST test
			critical (YES|NO) #REQUIRED
	>
	
	<!ELEMENT testset (test*) >
]>

<testset>

	<test critical="YES">
		<description>
			Do all contigs have the correct number of mappings?
		</description>

		<query>
			select C.contig_id,nreads,count(*) as mapping_count
			from CONTIG C, MAPPING M where C.contig_id=M.contig_id
			group by contig_id having nreads != mapping_count
		</query>
		
		<format>
			Contig {0,number,#} has nreads={1,number,#} but {2,number,#} mappings
		</format>
	</test>

	<test critical="YES">
		<description>
			Are there any orphan contigs?
		</description>
		
		<query>
			select contig_id,C.created,length,name
			from CONTIG C left join PROJECT P using(project_id)
			where C.nreads = 0
		</query>
		
		<format>
			Contig {0,number,#} created at {1,time} on {1,date}, length {2,number,#}bp, in project {3}, has nreads=0
		</format>
	</test>

	<test critical="YES">
		<description>
			Are there any duplicate reads?
		</description>
		
		<query>
		        select R.readname,DR.hits,CC.contig_id,P.name,CC.length,CC.nreads,CC.created,M.cstart,M.cfinish,M.direction
		        from DUPLICATEREADS DR left join (READINFO R,SEQ2READ SR,MAPPING M,CURRENTCONTIGS CC,PROJECT P)
		        on (DR.read_id=R.read_id)
		        where R.read_id=SR.read_id and SR.seq_id=M.seq_id and M.contig_id=CC.contig_id and CC.project_id=P.project_id
		        order by DR.read_id asc,CC.contig_id asc
		</query>
		
		<format>
			Read {0} appears {1,number,#} times and is in current contig {2,number,#} ({3}, {4,number,#} bp, {5,number,#} reads, created at {6,time} on {6,date}) from {7,number,#} to {8,number,#} in {9} sense
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all mappings correspond to contigs?
		</description>
		
		<query>
			select mapping_id,seq_id,MAPPING.contig_id
			from MAPPING left join CONTIG using(contig_id)
			where CONTIG.contig_id is null
		</query>
		
		<format>
			Mapping {0,number,#} for sequence {1,number,#} refers to non-existent contig {2,number,#}
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all contig-to-sequence mappings have valid sequence data?
		</description>

		<query>
			select contig_id,mapping_id,MAPPING.seq_id
			from MAPPING left join SEQUENCE using(seq_id)
			where sequence is null or quality is null
		</query>
		
		<format>
			Mapping {1,number,#} in contig {0,number,#} has undefined sequence {2,number,#}
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all mappings have a corresponding read?
		</description>

		<query>
			select contig_id,mapping_id,MAPPING.seq_id from MAPPING left join (SEQ2READ,READINFO)
			on (MAPPING.seq_id = SEQ2READ.seq_id and SEQ2READ.read_id = READINFO.read_id)
			where readname is null
		</query>
		
		<format>
			Mapping {1,number,#} in contig {0,number,#} has sequence {2,number,#} with undefined read
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all sequences have quality clipping data?
		</description>

		<query>
			select SEQUENCE.seq_id from SEQUENCE left join QUALITYCLIP
			using(seq_id)
			where QUALITYCLIP.seq_id is null
		</query>
		
		<format>
			Sequence {0,number,#} has no quality clipping data
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all sequences have a corresponding sequence-to-read mapping?
		</description>
		
		<query>

			select SEQUENCE.seq_id from SEQUENCE left join SEQ2READ
			using (seq_id)
			where SEQ2READ.seq_id is null
		</query>
		
		<format>
			Sequence {0,number,#} has no associated sequence-to-read mapping
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all sequences with a sequence-to-read mapping have a valid read?
		</description>

		<query>
			select SEQUENCE.seq_id,SEQ2READ.read_id from SEQUENCE left join (SEQ2READ,READINFO)
			on (SEQUENCE.seq_id = SEQ2READ.seq_id and SEQ2READ.read_id = READINFO.read_id)
			where readname is null and SEQ2READ.read_id is not null
		</query>
		
		<format>
			Sequence {0,number,#} has no associated read (read_id is {1,number,#})
		</format>
	</test>

	<test critical="YES">
		<description>
			Do all reads have valid sequence data?
		</description>

		<query>
			select READINFO.read_id,readname from READINFO left join
			(SEQ2READ,SEQUENCE)
			on (READINFO.read_id = SEQ2READ.read_id and SEQ2READ.seq_id = SEQUENCE.seq_id)
			where sequence is null or quality is null
		</query>
		
		<format>
			Read {0,number,#} ({1}) has no associated sequence
		</format>
	</test>

	<test critical="NO">
		<description>
			Do all reads have a template?
		</description>

		<query>
			select read_id,readname from READINFO left join TEMPLATE
			using (template_id)
			where name is null
		</query>
		
		<format>
			Read {0,number,#} ({1}) has no associated template
		</format>
	</test>

	<test critical="NO">
		<description>
			Do all templates have a ligation?
		</description>

		<query>
			select template_id,TEMPLATE.name from TEMPLATE left join LIGATION
			using (ligation_id)
			where LIGATION.name is null
		</query>
		
		<format>
			Template {0,number,#} ({1}) has no associated ligation
		</format>
	</test>

	<test critical="NO">
		<description>
			Do all ligations have a clone?
		</description>

		<query>
			select ligation_id,LIGATION.name from LIGATION left join CLONE
			using(clone_id)
			where CLONE.name is null
		</query>
		
		<format>
			Ligation {0,number,#} ({1}) has no associated clone
		</format>
	</test>

</testset>
